// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMsnBrmanTWYRAJX1pFYA10C-IzOiNUf4',
    appId: '1:864060408584:web:618b76c7a7a878655c62bd',
    messagingSenderId: '864060408584',
    projectId: 'flutter-bloc-firebase-cr-34925',
    authDomain: 'flutter-bloc-firebase-cr-34925.firebaseapp.com',
    storageBucket: 'flutter-bloc-firebase-cr-34925.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnkHdtUKZ4aAVs6-FKV78KhIXHzvb7uNQ',
    appId: '1:864060408584:android:fcd81a5ab91b05415c62bd',
    messagingSenderId: '864060408584',
    projectId: 'flutter-bloc-firebase-cr-34925',
    storageBucket: 'flutter-bloc-firebase-cr-34925.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUjLP1125PUsWibzT-TLiPYjbL_PWCjc0',
    appId: '1:864060408584:ios:d68955c37e605d4b5c62bd',
    messagingSenderId: '864060408584',
    projectId: 'flutter-bloc-firebase-cr-34925',
    storageBucket: 'flutter-bloc-firebase-cr-34925.appspot.com',
    iosBundleId: 'com.example.flutterBlocFirebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUjLP1125PUsWibzT-TLiPYjbL_PWCjc0',
    appId: '1:864060408584:ios:dda3ee5c3a3631035c62bd',
    messagingSenderId: '864060408584',
    projectId: 'flutter-bloc-firebase-cr-34925',
    storageBucket: 'flutter-bloc-firebase-cr-34925.appspot.com',
    iosBundleId: 'com.example.flutterBlocFirebaseCrud.RunnerTests',
  );
}
